name: flutter_clean_application
description: A plugin that provides core elements for implementing the application layer of a Clean Architecture
version: 1.1.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  meta: ^1.8.0

  # Layers
  flutter_clean_domain:
    git:
      url: git@github.com:fabriziocacicia/flutter_clean_domain.git
      ref: v1.3.0


dev_dependencies:
  # Linting and Code analysis
  dart_lint_rules:
    git:
      url: git@github.com:fabriziocacicia/dart_lint_rules.git
      ref: v0.1.0

  # Testing
  test: ^1.21.5