name: flutter_clean_application
description: A plugin that provides core elements for implementing the application layer of a Clean Architecture
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  # Layers
  flutter_clean_domain:
    git:
      url: git@github.com:fabriziocacicia/flutter_clean_domain.git
      ref: main


dev_dependencies:
  # Linting and Code analysis
  dart_lint_rules:
    git:
      url: git@github.com:fabriziocacicia/dart_lint_rules.git
      ref: v0.2.0

  # Testing
  test: ^1.22.0
